import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <div className='spheresWrapper'>
          <div className='sphere1'></div>
          <div className='sphere2'></div>
          <div className='sphere3'></div>
        </div>
      </body>
    </html>
  );
}
