import "./globals.css";


export const metadata = {
  title: "L project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/images/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/svg+xml" href="/images/favicon.svg" />
        <link rel="shortcut icon" href="/images/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png" />
        <meta name="apple-mobile-web-app-title" content="L" />
        <link rel="manifest" href="/images/site.webmanifest" />
      </head>
      <body>
        {children}
        <div className='spheresWrapper'>
          <div className='sphere1'></div>
          <div className='sphere2'></div>
          <div className='sphere3'></div>
        </div>
      </body>
    </html>
  );
}
